name: MyPA BE Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clone env repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ENV_REPO }}
          token: ${{ secrets.ENV_TOKEN }}
          path: .envs

      - name: Copy env files
        run: cp .envs/${{ secrets.ENV_FILE_NAME }} .env

      - name: Run test with env
        run: |
          set -a
          source .env
          set +a
          ./gradlew test